CREATE TABLE COLLATERAL_EAA(
ID        VARCHAR(32) PRIMARY KEY NOT NULL, 
EA01AQ01  VARCHAR(80),
EA01AS01  VARCHAR(3),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EA01AH(
ID        VARCHAR(32) PRIMARY KEY NOT NULL, 
BATCH_ID  VARCHAR(32),
EA01AD01  VARCHAR(2 ),
EA01AI01  VARCHAR(40),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EBA(
ID         VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID   VARCHAR(32),
EB01AD06   VARCHAR(2 ),
EB01AD07   VARCHAR(2 ),
EB01AD03   VARCHAR(2 ),
EB01AD04   VARCHAR(2 ),
EB01AR01   VARCHAR(10),
EB01AD05   VARCHAR(3 ),
EB01AJ01   VARCHAR(15),
EB01AJ02   VARCHAR(15),
EB01AR02   VARCHAR(10),
EB01AD01   VARCHAR(1 ),
EB01AD02   VARCHAR(1 ),
EB01AR03   VARCHAR(10),
EB01BS01   VARCHAR(5 ),
EB01CS01   VARCHAR(5 ),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EB01BH(
ID          VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID    VARCHAR(32),
PARENT_ID   VARCHAR(32),
EB01BD01    VARCHAR(1 ),
EB01BQ01    VARCHAR(80),
EB01BD02    VARCHAR(2 ),
EB01BI01    VARCHAR(40),
EB01BD03    VARCHAR(2 ),
EB01BD04    VARCHAR(3 ),
EB01BJ01    VARCHAR(15),
EB01BD05    VARCHAR(1 ),
EB01BI02    VARCHAR(6 ),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EB01C(
ID         VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID   VARCHAR(32),
PARENT_ID  VARCHAR(32),
EB01CI01   VARCHAR(20),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_ECA(
ID          VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID    VARCHAR(32),
EC01AD05    VARCHAR(1 ),
EC01AD06    VARCHAR(2 ),
EC01AD03    VARCHAR(2 ),
EC01AR01    VARCHAR(10),
EC01AD04    VARCHAR(3 ),
EC01AJ01    VARCHAR(15),
EC01AR02    VARCHAR(10),
EC01AD01    VARCHAR(1 ),
EC01AD02    VARCHAR(1 ),
EC01AR03    VARCHAR(10),
EC01BS01    VARCHAR(5 ),
EC01CS01    VARCHAR(5 ),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EC01BH(
ID          VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID    VARCHAR(32),
PARENT_ID   VARCHAR(32),
EC01BD01    VARCHAR(1 ),
EC01BQ01    VARCHAR(80),
EC01BD02    VARCHAR(2 ),
EC01BI01    VARCHAR(40),
EC01BD03    VARCHAR(1 ),
EC01BD04    VARCHAR(3 ),
EC01BJ01    VARCHAR(15),
EC01BD05    VARCHAR(1 ),
EC01BI02    VARCHAR(6 ),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EC01C(
ID         VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID   VARCHAR(32),
PARENT_ID  VARCHAR(32),
EC01CI01   VARCHAR(20),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_EDA(
ID         VARCHAR(32) PRIMARY KEY NOT NULL,
ED01AI01   VARCHAR(6 ),
ED01AD01   VARCHAR(1 ),
ED01AJ01   VARCHAR(15),
ED01AD02   VARCHAR(3 ),
ED01AR01   VARCHAR(10),
ED01AR02   VARCHAR(10),
ED01AD03   VARCHAR(1 ),
ED01AD04   VARCHAR(1 ),
ED01AD05   VARCHAR(2 ),
ED01BS01   VARCHAR(5 ),
ED01CS01   VARCHAR(5 ),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_ED01BH(
ID          VARCHAR(32 ) PRIMARY KEY NOT NULL,
BATCH_ID    VARCHAR(32 ),
ED01BD01    VARCHAR(2  ),
ED01BD02    VARCHAR(1  ),
ED01BI01    VARCHAR(40 ),
ED01BD03    VARCHAR(2  ),
ED01BJ01    VARCHAR(15 ),
ED01BD04    VARCHAR(3  ),
ED01BD05    VARCHAR(1  ),
ED01BR01    VARCHAR(10 ),
ED01BD06    VARCHAR(1  ),
ED01BQ01    VARCHAR(80 ),
ED01BD07    VARCHAR(2  ),
ED01BI02    VARCHAR(40 ),
ED01BQ02    VARCHAR(200),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE COLLATERAL_ED01CH(
ID          VARCHAR(32) PRIMARY KEY NOT NULL,
BATCH_ID    VARCHAR(32),
ED01CD01    VARCHAR(2 ),
ED01CJ01    VARCHAR(15),
ED01CD02    VARCHAR(3 ),
ED01CD03    VARCHAR(1 ),
ED01CQ01    VARCHAR(80),
ED01CD04    VARCHAR(2 ),
ED01CI01    VARCHAR(40),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ),
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE
    CR_PBOC_R103
    (
        ID VARCHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        MSG_START_FLAG VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        MSG_VERSION VARCHAR(5) COLLATE Chinese_PRC_CI_AS,
        MSG_SND_CODE VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        MSG_RCV_CODE VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        MSG_GEN_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        MSG_TYPE VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        MSG_ID VARCHAR(16) COLLATE Chinese_PRC_CI_AS,
        MSG_RSV VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        QUERY_ORG_CODE VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        USER_CODE VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        PASSWORD VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        ORIGINATE_ORG_CODE VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        ORIGINATE_USER_CODE VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        ENT_NAME VARCHAR(80) COLLATE Chinese_PRC_CI_AS,
        ENT_CERT_TYPE VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        ENT_CERT_NUM VARCHAR(40) COLLATE Chinese_PRC_CI_AS,
        QUERY_REASON VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        SERVICE_CODE VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        QUERY_DATE VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        CREATE_USER VARCHAR(20) COLLATE Chinese_PRC_CI_AS,
        CREATE_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        CHECK_USER VARCHAR(20) COLLATE Chinese_PRC_CI_AS,
        CHECK_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        SEND_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RESP_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        STATUS VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        DIGITAL_SIGNATURE VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        PRIMARY KEY (ID)
    );

CREATE TABLE CR_PBOC_R104(
ID                    VARCHAR(32  ) PRIMARY KEY NOT NULL,
RESULT_CODE           VARCHAR(6   ),
RESULT_DESC           VARCHAR(100 ),
REPORT_NAME           VARCHAR(27  ),
REPORT_MESSAGE_PATH   VARCHAR(256 ),
RECORD_STATUS         VARCHAR(2   ),
RECEIPT_TIME          VARCHAR(14  ),
RSV1      VARCHAR(2  ),
RSV2      VARCHAR(8  ),
RSV3      VARCHAR(8  ),
RSV4      VARCHAR(14 ) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
RSV5      VARCHAR(14 ), 
RSV6      VARCHAR(32 ),
RSV7      VARCHAR(64 ),
RSV8      VARCHAR(60 ),
RSV9      VARCHAR(512),
RSV10     VARCHAR(1024)
)

CREATE TABLE
    COLLATERAL_ENT_QUERY
    (
        ID VARCHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        ENT_NAME VARCHAR(80) COLLATE Chinese_PRC_CI_AS,
        ENT_CERT_TYPE VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        ENT_CERT_NUM VARCHAR(40) COLLATE Chinese_PRC_CI_AS,
        QUERY_REASON VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        SERVICE_CODE VARCHAR(100) COLLATE Chinese_PRC_CI_AS,
        QUERY_DATE VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        CREATE_USER VARCHAR(20) COLLATE Chinese_PRC_CI_AS,
        CREATE_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        CHECK_USER VARCHAR(20) COLLATE Chinese_PRC_CI_AS,
        CHECK_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        SEND_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RESP_TIME VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RESP_ID VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RESP_CODE VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RESP_MSG VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        STATUS VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        IP VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        USE_SCAN VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV5 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        PRIMARY KEY (ID)
    );

--二代征信抵押物一级菜单
INSERT INTO FUNCTION_INFO(FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) 
VALUES ('10', '二代征信抵押物', '', 2.00, 1.00, '0', 11.00, NULL, '1', NULL, 'NULL', 'CRMS', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--授权
INSERT INTO ROLE_FUNC_REL(ROLE_ID, FUNCID) VALUES ( '202', '10');
INSERT INTO ROLE_FUNC_REL(ROLE_ID, FUNCID) VALUES ( '213', '10');
--新增 二级菜单  “抵押物及相关还款责任人查询” 
INSERT INTO FUNCTION_INFO(FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) 
VALUES ('888802', '抵押物及相关还款责任人查询', '/fpages/crms/ftl/QueryCollateralMake.ftl', 2.00, 0.00, '10', 1.00, '1', '1', NULL, 'NULL', 'CRMS', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--新增 二级菜单授权 “抵押物及相关还款责任人查询”
INSERT INTO ROLE_FUNC_REL( ROLE_ID, FUNCID) VALUES ( '213', '888802');
INSERT INTO ROLE_FUNC_REL( ROLE_ID, FUNCID) VALUES ( '202', '888802');
--抵押物新增参数配置
INSERT INTO SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER, PARAM_VAL, SYS_NAME) VALUES ('Collateral', 'SEND_PATH', '企业抵押物查询发送文件保存路径', null, '4', 'F', 'F', null, null, null, '/tmp/snd_collateral/', 'CRMS');
INSERT INTO SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER, PARAM_VAL, SYS_NAME) VALUES ('Collateral', 'RECV_PATH', '企业抵押物查询接收文件保存路径', null, '4', 'F', 'F', null, null, null, '/tmp/rcv_collateral/', 'CRMS');


















































































