package com.huateng.report.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-12T18:43:09.128+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", name = "PbocPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PbocPort {

    @WebMethod
    @WebResult(name = "bsCreditReportQueryReqResponse", targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", partName = "bsCreditReportQueryReqResponse")
    public BsCreditReportQueryReqResponse bsCreditReportQueryReq(

        @WebParam(partName = "bsCreditReportQueryReqRequest", name = "bsCreditReportQueryReqRequest", targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/")
        BsCreditReportQueryReqRequest bsCreditReportQueryReqRequest
    );

    @WebMethod
    @WebResult(name = "psCreditReportQueryReqResponse", targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/", partName = "psCreditReportQueryReqResponse")
    public PsCreditReportQueryReqResponse psCreditReportQueryReq(

        @WebParam(partName = "psCreditReportQueryReqRequest", name = "psCreditReportQueryReqRequest", targetNamespace = "http://ws.serviceaccept.ws.service.query.channel.pbccrc.org/")
        PsCreditReportQueryReqRequest psCreditReportQueryReqRequest
    );
}
