--新增一代个人信息查询
INSERT INTO FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) VALUES ('666666', '一代个人信用信息查询', '/fpages/business/ftl/inqRequest.ftl', 2, 0, '30', 6, '1', '1', null, 'NULL', 'OTHER', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--授权
INSERT INTO ROLE_FUNC_REL(ID,ROLE_ID,FUNCID) VALUES(4247,'202','666666');
INSERT INTO ROLE_FUNC_REL(ID,ROLE_ID,FUNCID) VALUES(4248,'213','666666');
--批量二代个人征信爬网请求状态查询
INSERT INTO FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) VALUES ('666667', '批量二代个人征信爬网请求状态查询', '/fpages/business/ftl/PersonalCrawState.ftl', 2, 0, '30', 7, '1', '1', null, 'NULL', 'OTHER', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--授权
INSERT INTO ROLE_FUNC_REL(ID,ROLE_ID,FUNCID) VALUES(4249,'202','666667');
INSERT INTO ROLE_FUNC_REL(ID,ROLE_ID,FUNCID) VALUES(4250,'213','666667');
--批量二代企业请求状态查询
INSERT INTO FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) VALUES ('666668', '批量二代企业征信请求状态查询', '/fpages/crms/ftl/CorpStateQuery.ftl', 2, 0, '40', 5, '1', '1', null, 'NULL', 'OTHER', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--授权
INSERT INTO ROLE_FUNC_REL(ID,ROLE_ID,FUNCID) VALUES(4251,'202','666668');
INSERT INTO ROLE_FUNC_REL(ID,ROLE_ID,FUNCID) VALUES(4252,'213','666668');



--新增_菜单_二代企业查询—提交企业征信报告查询请求(紧急) (by quxin 2020.02.24 from guokang 2020.02.05)
INSERT INTO FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) 
VALUES ('666671', '提交企业征信报告查询请求(紧急)', '/fpages/business/ftl/UrgentPbocQueryCorpMake.ftl', 2, 0, '40', 7, '1', '1', null, 'NULL', 'CRMS', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--新增_菜单_二代个人查询_提交二代个人征信报告爬网查询请求（紧急） (by quxin 2020.02.24 from guokang 2020.02.05)
INSERT INTO FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) 
VALUES ('666672', '提交二代个人征信报告爬网查询请求（紧急）', '/fpages/business/ftl/UrgentPbocQueryPersonalCrawl.ftl', 2, 0, '30', 9, '1', '1', null, 'NULL', 'CRMS', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
--新增_菜单_二代企业查询_一代企业信用信息查询 (by quxin 2020.02.24 from guokang 2020.02.11)
INSERT INTO FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, ICON_CLS, MISC) 
VALUES ('666673', '一代企业信用信息查询', '/fpages/business/ftl/CompanyReport.ftl', 2, 0, '40', 8, '1', '1', null, 'NULL', 'CRMS', '1', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');

--新增_权限 (by quxin from guokang 2020.02.24) 权限自己分配，这里先分配到 202‘系统管理审核员’
INSERT INTO ROLE_FUNC_REL(ROLE_ID, FUNCID) VALUES ( '202', '666671');
INSERT INTO ROLE_FUNC_REL(ROLE_ID, FUNCID) VALUES ( '202', '666672');
INSERT INTO ROLE_FUNC_REL(ROLE_ID, FUNCID) VALUES ( '202', '666673');
--修改_字典_字段值_data_dic (by quxin 2020.02.24 from guokang 2020.02.20)
UPDATE DATA_DIC SET DATA_NAME='CR_COM_ED06' WHERE DATA_TYPE_NAME='表名 ' AND DATA_NO='33';
--修改_表字段值_Report_Job_Config (by quxin 2020.02.24 from guokang 2020.02.20)
UPDATE Report_Job_Config SET JOB_TIME='0 0 1 1 * ? ' WHERE JOB_NAME='个人征信数据定时抽取' ;
UPDATE Report_Job_Config SET JOB_TIME='0 0 1 1 * ? ' WHERE JOB_NAME='企业征信数据定时抽取' ;

--修改_字段属性_长度 (by quxin 2020.02.25 from xuwenbo 2020.02.21)
ALTER table CR_COM_ED06 MODIFY ED060R01 VARCHAR(30);
ALTER table CR_COM_ED06 MODIFY ED060R02 VARCHAR(30);
ALTER table CR_COM_ED06 MODIFY ED060R03 VARCHAR(30);
ALTER table CR_COM_EB03BH MODIFY EB03BS02 VARCHAR(5);
ALTER table CR_COM_EB05AH MODIFY EB05AS03 VARCHAR(5);
