DROP TABLE CR_PER_PD01ZH;
DROP TABLE CR_PER_PD02ZH;
DROP TABLE CR_PER_PD03ZH;
DROP TABLE CR_PER_PF01ZH;
DROP TABLE CR_PER_PF02ZH;
DROP TABLE CR_PER_PF03ZH;
DROP TABLE CR_PER_PF04ZH;
DROP TABLE CR_PER_PF05ZH;
DROP TABLE CR_PER_PF06ZH;
DROP TABLE CR_PER_PF07ZH;
DROP TABLE CR_PER_PF08ZH;
DROP TABLE CR_PER_PG010H;
DROP TABLE CR_PER_PA01CH;

CREATE TABLE
    CR_PER_PD01ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PD01ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PD01ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PD01ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        PARENT_ID VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PD01ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PD02ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PD02ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PD02ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PD02ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PD02ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PD03ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PD03ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PD03ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PD03ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PD03ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF01ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF01ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF01ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF01ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF01ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF02ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF02ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF02ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF02ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF02ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF03ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF03ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF03ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF03ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF03ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF04ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF04ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF04ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF04ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF04ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF05ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF05ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF05ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF05ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF05ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF06ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF06ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF06ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF06ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF06ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF07ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF07ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF07ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF07ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF07ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PF08ZH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PF08ZD01 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PF08ZQ01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PF08ZR01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PF08ZH PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PG010H
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PG010D03 VARCHAR(1) COLLATE Chinese_PRC_CI_AS,
        PG010Q01 VARCHAR(200) COLLATE Chinese_PRC_CI_AS,
        PG010R01 VARCHAR(10) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PG010H PRIMARY KEY (id)
    );
	
CREATE TABLE
    CR_PER_PA01CH
    (
        id CHAR(32) NOT NULL,
        batch_id CHAR(32) COLLATE Chinese_PRC_CI_AS NOT NULL,
        PA01CD01 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        PA01CI01 VARCHAR(20) COLLATE Chinese_PRC_CI_AS,
        RSV1 VARCHAR(2) COLLATE Chinese_PRC_CI_AS,
        RSV2 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV3 VARCHAR(8) COLLATE Chinese_PRC_CI_AS,
        RSV4 VARCHAR(14) COLLATE Chinese_PRC_CI_AS DEFAULT 'CONVERT([varchar](4),getdate(),(112))',
        RSV5 VARCHAR(14) COLLATE Chinese_PRC_CI_AS,
        RSV6 VARCHAR(32) COLLATE Chinese_PRC_CI_AS,
        RSV7 VARCHAR(64) COLLATE Chinese_PRC_CI_AS,
        RSV8 VARCHAR(60) COLLATE Chinese_PRC_CI_AS,
        RSV9 VARCHAR(512) COLLATE Chinese_PRC_CI_AS,
        RSV10 VARCHAR(1024) COLLATE Chinese_PRC_CI_AS,
        CONSTRAINT PK_CR_PER_PA01CH PRIMARY KEY (id)
    );




