package com.huateng.report.utils;
/** 
* @author Grassy 
* @version 创建时间：2020年3月1日 下午9:11:42 
* 类说明 
*/
public enum TableEnum {
	CR_COM_EAA      ,
	CR_COM_EA01CH   ,
	CR_COM_ECA      ,
	CR_COM_EC020H   ,
	CR_COM_EC030H   ,
	CR_COM_EC050H   ,
	CR_COM_EBA      ,
	CR_COM_EBB      ,
	CR_COM_EB02AH   ,
	CR_COM_EB02BH   ,
	CR_COM_EB02CH   ,
	CR_COM_EBC      ,
	CR_COM_EB03AH   ,
	CR_COM_EB03BH   ,
	CR_COM_EBD      ,
	CR_COM_EBE      ,
	CR_COM_EB05AH   ,
	CR_COM_EB05BH   ,
	CR_COM_EDA      ,
	CR_COM_ED01     ,
	CR_COM_ED02     ,
	CR_COM_ED03     ,
	CR_COM_ED01B    ,
	CR_COM_ED01C    ,
	CR_COM_ED01BH   ,
	CR_COM_ED01CH   ,
	CR_COM_EDB      ,
	CR_COM_ED04     ,
	CR_COM_ED04B    ,
	CR_COM_ED05     ,
	CR_COM_EDC      ,
	CR_COM_ED06     ,
	CR_COM_ED07     ,
	CR_COM_ED08     ,
	CR_COM_ED09     ,
	CR_COM_EEA      ,
	CR_COM_EE01BH   ,
	CR_COM_EFA      ,
	CR_COM_EFB      ,
	CR_COM_EFC      ,
	CR_COM_EFD      ,
	CR_COM_EF05BH   ,
	CR_COM_EFE      ,
	CR_COM_EFF      ,
	CR_COM_EFG      ,
	CR_COM_EGA      ,
	CR_COM_EHA      ,
	CR_COM_EIA
}
